# Generated by Django 4.2 on 2023-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='category',
        ),
    ]
